FROM alpine

ARG BUILD_REPO
ARG BUILD_OWNER_REPO
ARG GIT_FOLDER=/var/www/html

LABEL maintainer="Ivan Kuchin"
LABEL org.opencontainers.image.source="https://github.com/${BUILD_OWNER_REPO}"

COPY . ${GIT_FOLDER}

